"""AI DTO sub-generator for the AI Layer.

Generates shared AI DTOs in ``<basePackage>.ai.dto`` that are not already
produced by individual sub-generators.  This includes request/response DTOs
for entity and standalone AI controllers, ``ClassificationResultDTO``, and
the ``TypedResponseResult<T>`` generic wrapper.

The following DTOs are generated here (Req 18.1–18.3):
- AiSearchRequestDTO
- AiGenerateRequestDTO
- AiClassifyRequestDTO
- AiChatRequestDTO
- AiChatResponseDTO
- StandaloneGenerateRequestDTO
- StandaloneQueryRequestDTO
- StandaloneQueryResponseDTO
- ClassificationResultDTO

DTOs already generated by other sub-generators are NOT duplicated:
- EvaluationResultDTO (EvaluatorGenerator)
- AiResponseWithEvaluationDTO (EvaluatorGenerator)
- AiErrorResponseDTO (ExceptionGenerator)
- TypedResponseResult<T> (TypedResponseGenerator)
- etc.

Requirements: 18.1–18.3
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import jinja2


class AiDtoGenerator:
    """Generates shared AI DTO Java files from the AI_Layer definition."""

    def __init__(self, jinja_env: "jinja2.Environment"):
        self.jinja_env = jinja_env

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        ai_layer: dict,
        base_package: str,
        output_dirs: dict[str, Path],
    ) -> list[tuple[str, str]]:
        """Generate shared AI DTO Java files.

        Returns a list of ``(filepath, content)`` tuples where *filepath* is
        relative to the project source root.

        When no AI features are configured (no entityCapabilities and no
        standaloneOperations), no DTO files are generated.
        """
        entity_caps = ai_layer.get("entityCapabilities", [])
        standalone_ops = ai_layer.get("standaloneOperations", [])

        if not entity_caps and not standalone_ops:
            return []

        results: list[tuple[str, str]] = []
        dto_dir = output_dirs.get("dto", Path("ai/dto"))
        ctx = {"base_package": base_package}

        # 1. Request/response DTOs (Req 18.1)
        results.append((
            str(dto_dir / "AiSearchRequestDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "AiSearchRequestDTO",
                "dto_type": "search_request",
            }),
        ))

        results.append((
            str(dto_dir / "AiGenerateRequestDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "AiGenerateRequestDTO",
                "dto_type": "generate_request",
            }),
        ))

        results.append((
            str(dto_dir / "AiClassifyRequestDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "AiClassifyRequestDTO",
                "dto_type": "classify_request",
            }),
        ))

        results.append((
            str(dto_dir / "AiChatRequestDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "AiChatRequestDTO",
                "dto_type": "chat_request",
            }),
        ))

        results.append((
            str(dto_dir / "AiChatResponseDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "AiChatResponseDTO",
                "dto_type": "chat_response",
            }),
        ))

        results.append((
            str(dto_dir / "StandaloneGenerateRequestDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "StandaloneGenerateRequestDTO",
                "dto_type": "standalone_generate_request",
            }),
        ))

        results.append((
            str(dto_dir / "StandaloneQueryRequestDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "StandaloneQueryRequestDTO",
                "dto_type": "standalone_query_request",
            }),
        ))

        results.append((
            str(dto_dir / "StandaloneQueryResponseDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "StandaloneQueryResponseDTO",
                "dto_type": "standalone_query_response",
            }),
        ))

        # 2. ClassificationResultDTO (Req 18.3)
        results.append((
            str(dto_dir / "ClassificationResultDTO.java"),
            self._render("dto/ai_dtos.java.j2", {
                **ctx,
                "dto_name": "ClassificationResultDTO",
                "dto_type": "classification_result",
            }),
        ))

        return results

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _render(self, template_name: str, ctx: dict) -> str:
        """Render a Jinja2 template under the ai/ prefix."""
        template = self.jinja_env.get_template(f"ai/{template_name}")
        return template.render(**ctx)
