"""Token budget sub-generator for the AI Layer.

Generates TokenBudgetService, TokenBudgetController, and token budget DTOs
(TokenUsageDTO, TokenUsageSummaryDTO, TokenBudgetExceededResponseDTO).

Note: TokenBudgetExceededException is already generated by ExceptionGenerator
(Req 14.22, 15.27) — this generator does NOT regenerate it.

Requirements: 15.17–15.33
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import jinja2

# Default configuration values
DEFAULT_ENFORCEMENT_ACTION = "block"
DEFAULT_WARNING_THRESHOLD_PERCENT = 80
VALID_ENFORCEMENT_ACTIONS = {"block", "warn", "log"}


class TokenBudgetGenerator:
    """Generates token budget Java files from the AI_Layer definition.

    Follows the same sub-generator pattern as ObservabilityGenerator:
    receives parsed definition data, checks whether the feature is
    enabled, loads and renders Jinja2 templates, and returns a list
    of ``(filepath, content)`` tuples.
    """

    def __init__(self, jinja_env: "jinja2.Environment"):
        self.jinja_env = jinja_env

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        token_budget: dict | None,
        base_package: str,
        output_dirs: dict[str, Path],
    ) -> list[tuple[str, str]]:
        """Generate token budget Java files.

        Returns a list of ``(filepath, content)`` tuples where *filepath*
        is relative to the project source root.

        Req 15.29: When tokenBudget is absent or ``enabled`` is false,
        no token budget files are generated.
        """
        if not token_budget or not token_budget.get("enabled", False):
            return []

        results: list[tuple[str, str]] = []

        budget_dir = output_dirs.get("budget", Path("ai/budget"))
        controller_dir = output_dirs.get("controller", Path("ai/controller"))
        dto_dir = output_dirs.get("dto", Path("ai/dto"))

        # Build template context
        ctx = self._build_context(token_budget, base_package)

        # 1. TokenBudgetService (Req 15.17–15.23, 15.31–15.33)
        results.append((
            str(budget_dir / "TokenBudgetService.java"),
            self._render("budget/token_budget_service.java.j2", ctx),
        ))

        # 2. TokenBudgetController (Req 15.25)
        results.append((
            str(controller_dir / "TokenBudgetController.java"),
            self._render(
                "controller/token_budget_controller.java.j2",
                {"base_package": base_package},
            ),
        ))

        # 3. TokenUsageDTO (Req 15.26)
        results.append((
            str(dto_dir / "TokenUsageDTO.java"),
            self._render(
                "dto/token_usage_dto.java.j2",
                {"base_package": base_package},
            ),
        ))

        # 4. TokenUsageSummaryDTO (Req 15.26)
        results.append((
            str(dto_dir / "TokenUsageSummaryDTO.java"),
            self._render(
                "dto/token_usage_summary_dto.java.j2",
                {"base_package": base_package},
            ),
        ))

        # 5. TokenBudgetExceededResponseDTO (Req 15.26)
        results.append((
            str(dto_dir / "TokenBudgetExceededResponseDTO.java"),
            self._render(
                "dto/token_budget_exceeded_response_dto.java.j2",
                {"base_package": base_package},
            ),
        ))

        return results

    # ------------------------------------------------------------------
    # Context builders
    # ------------------------------------------------------------------

    def _build_context(self, token_budget: dict, base_package: str) -> dict:
        """Build the Jinja2 template context from the tokenBudget config."""
        provider_overrides = token_budget.get("providerOverrides", {}) or {}

        return {
            "base_package": base_package,
            "default_daily_limit": token_budget.get("defaultDailyLimitPerUser"),
            "default_monthly_limit": token_budget.get("defaultMonthlyLimitPerUser"),
            "provider_overrides": provider_overrides,
            "warning_threshold_percent": token_budget.get(
                "warningThresholdPercent", DEFAULT_WARNING_THRESHOLD_PERCENT
            ),
            "enforcement_action": token_budget.get(
                "enforcementAction", DEFAULT_ENFORCEMENT_ACTION
            ),
        }

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def _render(self, template_name: str, ctx: dict) -> str:
        """Render a Jinja2 template under the ai/ prefix."""
        template = self.jinja_env.get_template(f"ai/{template_name}")
        return template.render(**ctx)
