"""Repository templates for code generation.

The authorized SQL queries are generated by sql_builder.py (PyPika)
and injected into the template context by the repository generator.
Template variables like {{ authPagedQuery }} and {{ authCountQuery }}
contain pre-built SQL strings.
"""


class RepositoryTemplates:
    """Templates for repository interface generation."""

    REPOSITORY_TEMPLATE = '''package {{ packageName }};

import {{ entityPackage }}.{{ entityName }};
import org.springframework.data.r2dbc.repository.Query;
import org.springframework.data.r2dbc.repository.R2dbcRepository;
import org.springframework.stereotype.Repository;
import reactor.core.publisher.Mono;
import reactor.core.publisher.Flux;
{% if hasAuthorization %}import java.util.List;
{% endif %}
/**
 * Repository interface for {{ entityName }} entity.
 */
@Repository
public interface {{ className }} extends R2dbcRepository<{{ entityName }}, {{ idType }}> {
{% if hasSoftDelete %}
    @Query("SELECT * FROM {{ tableName }} WHERE {{ idColumn }} = :id AND deleted_at IS NULL")
    Mono<{{ entityName }}> findByIdAndDeletedAtIsNull({{ idType }} id);

    @Query("SELECT * FROM {{ tableName }} WHERE deleted_at IS NULL")
    Flux<{{ entityName }}> findAllByDeletedAtIsNull();

    @Query("{{ pagedQuery }}")
    Flux<{{ entityName }}> findAllPagedByDeletedAtIsNull(int size, long offset);

    @Query("{{ countQuery }}")
    Mono<Long> countByDeletedAtIsNull();
{% if hasAuthorization %}
    @Query("SELECT * FROM {{ tableName }} WHERE {{ idColumn }} IN (:ids) AND deleted_at IS NULL")
    Flux<{{ entityName }}> findAllByIdInAndDeletedAtIsNull(List<{{ idType }}> ids);

    @Query("{{ authPagedQuery }}")
    Flux<{{ entityName }}> findAllPagedAuthorized(Long authUserId, int size, long offset);

    @Query("{{ authCountQuery }}")
    Mono<Long> countAuthorized(Long authUserId);

    @Query("SELECT COUNT(DISTINCT e.{{ idColumn }}) FROM {{ tableName }} e " +
           "LEFT JOIN record_owner ro ON ro.table_name = :tableName AND ro.record_id = e.{{ idColumn }} " +
           "LEFT JOIN query_group_record qgr ON qgr.table_name = :tableName AND qgr.record_id = e.{{ idColumn }} " +
           "WHERE e.deleted_at IS NULL AND (ro.auth_user_id = :authUserId OR qgr.query_group_id IN (:groupIds))")
    Mono<Long> countOwnedOrShared(Long authUserId, String tableName, List<Long> groupIds);

    @Query("SELECT DISTINCT e.* FROM {{ tableName }} e " +
           "LEFT JOIN record_owner ro ON ro.table_name = :tableName AND ro.record_id = e.{{ idColumn }} " +
           "LEFT JOIN query_group_record qgr ON qgr.table_name = :tableName AND qgr.record_id = e.{{ idColumn }} " +
           "WHERE e.deleted_at IS NULL AND (ro.auth_user_id = :authUserId OR qgr.query_group_id IN (:groupIds)) " +
           "LIMIT :limit OFFSET :offset")
    Flux<{{ entityName }}> findAllPagedOwnedOrShared(Long authUserId, String tableName, List<Long> groupIds, int limit, long offset);
{% endif %}{% else %}
    @Query("{{ pagedQuery }}")
    Flux<{{ entityName }}> findAllPaged(int size, long offset);

    @Query("{{ countQuery }}")
    Mono<Long> countAll();
{% if hasAuthorization %}
    @Query("{{ authPagedQuery }}")
    Flux<{{ entityName }}> findAllPagedAuthorized(Long authUserId, int size, long offset);

    @Query("{{ authCountQuery }}")
    Mono<Long> countAuthorized(Long authUserId);

    @Query("SELECT COUNT(DISTINCT e.{{ idColumn }}) FROM {{ tableName }} e " +
           "LEFT JOIN record_owner ro ON ro.table_name = :tableName AND ro.record_id = e.{{ idColumn }} " +
           "LEFT JOIN query_group_record qgr ON qgr.table_name = :tableName AND qgr.record_id = e.{{ idColumn }} " +
           "WHERE ro.auth_user_id = :authUserId OR qgr.query_group_id IN (:groupIds)")
    Mono<Long> countOwnedOrShared(Long authUserId, String tableName, List<Long> groupIds);

    @Query("SELECT DISTINCT e.* FROM {{ tableName }} e " +
           "LEFT JOIN record_owner ro ON ro.table_name = :tableName AND ro.record_id = e.{{ idColumn }} " +
           "LEFT JOIN query_group_record qgr ON qgr.table_name = :tableName AND qgr.record_id = e.{{ idColumn }} " +
           "WHERE ro.auth_user_id = :authUserId OR qgr.query_group_id IN (:groupIds) " +
           "LIMIT :limit OFFSET :offset")
    Flux<{{ entityName }}> findAllPagedOwnedOrShared(Long authUserId, String tableName, List<Long> groupIds, int limit, long offset);
{% endif %}{% endif %}{% if isEntityAuthorization %}

    @Query("SELECT * FROM {{ tableName }} WHERE entity_type = :entityType AND entity_id = :entityId")
    Flux<{{ entityName }}> findByEntityTypeAndEntityId(String entityType, Long entityId);

    @Query("SELECT * FROM {{ tableName }} WHERE entity_type = :entityType AND auth_user_id = :authUserId")
    Flux<{{ entityName }}> findByEntityTypeAndAuthUserId(String entityType, Long authUserId);

    @Query("SELECT * FROM {{ tableName }} WHERE entity_type = :entityType AND group_id = :groupId")
    Flux<{{ entityName }}> findByEntityTypeAndGroupId(String entityType, Long groupId);
{% endif %}{% if isUserGroupMembership %}

    @Query("SELECT * FROM {{ tableName }} WHERE auth_user_id = :authUserId")
    Flux<{{ entityName }}> findByAuthUserId(Long authUserId);

    @Query("SELECT * FROM {{ tableName }} WHERE auth_user_id = :authUserId AND group_id = :groupId")
    Mono<{{ entityName }}> findByAuthUserIdAndGroupId(Long authUserId, Long groupId);
{% endif %}{% if singleRecordPerUser %}

    @Query("SELECT * FROM {{ tableName }} WHERE {{ idColumn }} IN " +
           "(SELECT record_id FROM record_owner WHERE table_name = '{{ tableName }}' AND auth_user_id = :authUserId){% if hasSoftDelete %} AND deleted_at IS NULL{% endif %}")
    Mono<{{ entityName }}> findByOwnerUserId(Long authUserId);
{% endif %}
}
'''
